"""empty message

Revision ID: b1bfa4865509
Revises: 86fac7180629
Create Date: 2022-05-17 15:33:37.393865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bfa4865509'
down_revision = '86fac7180629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
